"""initial

Revision ID: 7ab7bca47ddf
Revises: 
Create Date: 2025-01-20 10:57:21.898089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab7bca47ddf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('routine_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('initial_weight', sa.Integer(), nullable=True),
    sa.Column('current_weight', sa.Integer(), nullable=True),
    sa.Column('initial_reps', sa.Integer(), nullable=True),
    sa.Column('current_reps', sa.Integer(), nullable=True),
    sa.Column('initial_sets', sa.Integer(), nullable=True),
    sa.Column('current_sets', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('day_of_the_week', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_routine_items_exercise_id_exercises')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_routine_items_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routine_items')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
