"""up

Revision ID: cb3e8bc6321b
Revises: 7ab7bca47ddf
Create Date: 2025-01-21 18:37:14.747233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3e8bc6321b'
down_revision = '7ab7bca47ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
